# Exported from Render on 2025-05-17T19:32:38Z
databases:
- name: mithlanchal-dbv2
  databaseName: store_lt18
  user: admin
  plan: free
  region: oregon
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"
